{{- if and (ne .Values.loadBalancer.type "disable") (ne .Values.loadBalancer.type "gclb") -}}
{{- $fullName := include "livekit-server.fullname" . -}}
{{- $svcPort := .Values.loadBalancer.servicePort -}}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
apiVersion: networking.k8s.io/v1
spec:
  ingressClassName: nginx
  rules:
  # In order to work with cert manager on DO, we cannot set us as a default backend
  {{- range .Values.loadBalancer.tls }}
  {{- range .hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
  {{- end }}
  {{- end }}
{{- if ne .Values.loadBalancer.type "gke-vpc-native" }}
{{- with .Values.loadBalancer }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    {{- if .hosts }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName | quote }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
