apiVersion: v1
kind: Service
metadata:
  name: {{ include "livekit-server.fullname" . }}
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.loadBalancer.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
    - name: rtc-tcp
      port: {{ .Values.livekit.rtc.tcp_port }}
      protocol: TCP
      targetPort: rtc-tcp
    - port: {{ .Values.livekit.prometheus_port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "livekit-server.selectorLabels" . | nindent 4 }}
  loadBalancerIP: {{ .Values.loadBalancer.loadBalancerIP }}
